
name: 'Push promtool image'

on:
  pull_request:
    types: [ labeled, opened, reopened, synchronize ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: sre-promtool
  USER: humayunalamho

jobs:
  publish:
    name: 'Branch Publish'
    permissions:
      contents: read
      packages: write
      security-events: write
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'promtool') == true
    steps:
      #Checks-out our repository under $GITHUB_WORKSPACE, so our workflow can access it.
      - name: Checkout
        uses: actions/checkout@v3


        #Logs into Github registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        run: docker build -t ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.IMAGE_NAME }}:v2 ${GITHUB_WORKSPACE}/monitoring-as-code/tools/promtool

      - name: Push image to GitHub Container Registry
        run: docker push ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.IMAGE_NAME }}:v3