name: ZAP
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: owasp/zap2docker-stable
      options: -v /__w/actions-test-repo/actions-test-repo:/zap/wrk/:rw
    steps:
      - uses: actions/checkout@v2
      - name: run zap
        if: always()
        run: zap-baseline.py -t https://www.example.com -g gen.conf -w testreport.md